
name: Dummy test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  echo-substitutions:
    runs-on: ubuntu-latest

    steps:
      - name: Test GHA expressions language
        run: |
          echo null: ${{ null }}

          echo bools
          echo true: ${{ true }}
          echo false: ${{ false }}

          echo numbers
          echo 0: ${{ 0 }}
          echo 1: ${{ 1 }}
          echo 10: ${{ 10 }}
          echo -0: ${{ -0 }}
          echo -0.0: ${{ -0.0 }}
          echo -1: ${{ -1 }}

          echo strings

          echo empty string: ${{ '' }}
          echo \'potato\': ${{ 'potato' }}

          echo "no array or object literals!"
          echo "can't subsitute and not provide an expression"

      - name: Test logical and
        run: |
          echo 'null && 1': ${{ null && 1 }}, ${{ toJSON( null && 1 ) }}
          echo '0 && 1': ${{ 0 && 1 }}, ${{ toJSON( 0 && 1 ) }}
          echo '1 && 1': ${{ 1 && 1 }}, ${{ toJSON( 1 && 1 ) }}
          echo '2 && 1': ${{ 2 && 1 }}, ${{ toJSON( 2 && 1 ) }}
          echo '2 && 2': ${{ 2 && 2 }}, ${{ toJSON( 2 && 2 ) }}
          echo "'' && 1": ${{ '' && 1 }}, ${{ toJSON( '' && 1 ) }}
          echo "'potato' && 1": ${{ 'potato' && 1 }}, ${{ toJSON( 'potato' && 1 ) }}
          echo "null && 'a' || 'b'": ${{ null && 'a' || 'b' }}, ${{ toJSON( null && 'a' || 'b' }}
          echo "true && 'a' || 'b'": ${{ true && 'a' || 'b' }}, ${{ toJSON( true && 'a' || 'b' }}
          echo "false && 'a' || 'b'": ${{ false && 'a' || 'b' }}, ${{ toJSON( false && 'a' || 'b' }}

  test-reading-from-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - label: SQLite

          - label: SQLite, full HTTP APIs
            api: full-http

          - label: Postgres
            postgres: postgres

          - label: Postgres, full HTTP APIs
            postgres: postgres
            api: full-http

    name: ${{ matrix.label }}
    steps:
      - name: Echo
        env:
          POSTGRES: ${{ matrix.postgres }}
          API: ${{ matrix.api }}
        run: |
          echo label: ${{ matrix.label }}
          echo api: ${{ matrix.api }}
          echo postgres: ${{ matrix.postgres }}
          echo
          echo label: ${{ toJSON(matrix.label) }}
          echo api: ${{ toJSON(matrix.api) }}
          echo postgres: ${{ toJSON(matrix.postgres) }}
          echo
          echo 'postgres && 1': ${{ matrix.postgres && 1 }} ${{ toJSON(matrix.postgres && 1) }}
          echo 'api && 1': ${{ matrix.api && 1 }} ${{ toJSON(matrix.api && 1) }}
          echo POSTGRES=${POSTGRES:-<NOT SET>}
          echo API=${API:-<NOT SET>}
