name: Dummy test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Runs a set of commands using the runners shell
      - name: Test GHA expressions language
        run: |
          echo null: ${{ null }}

          echo bools
          echo true: ${{ true }}
          echo false: ${{ false }}

          echo numbers
          echo 0: ${{ 0 }}
          echo 1: ${{ 1 }}
          echo 10: ${{ 10 }}
          echo -0: ${{ -0 }}
          echo -1: ${{ -1 }}

          echo arrays
          echo []: ${{ [] }}
          echo [1]: ${{ [1] }}
          echo [1, 2]: ${{ [1, 2] }}
          echo [1, 2, "hello"]: ${{ [1, 2, "hello"] }}

          echo objects
          echo {}: ${{ {} }}
          echo {"hello": "world"}: ${{ {"hello": "world"} }}
          echo {"hello": "world", "potato": "tasty"}: ${{ {"hello": "world", "potato": "tasty"} }}
          echo {"a": "A", "a": "A"}: ${{ {"a": "A", "a": "A"} }}




